name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [v20.9.0]

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/jasongin/nodejs -b napi-libnode-${{ matrix.version }} --single-branch .

      - name: Build on *nix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ./configure --shared; make -j4

      - name: Build on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          .\vcbuild.bat x64 release dll openssl-no-asm

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: napi-${{ matrix.os }}-amd64-${{ matrix.version }}
          path: |
            out/Release
